[workspace]
channels = ["conda-forge", "wug"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[package]
name = "della-wonders"
version = "1.0.3"
description = "Store-and-forward HTTP proxy for airgapped environments"
authors = ["Della Wonders Team <dev@example.com>"]
homepage = "https://github.com/professorwug/della_wonders"
repository = "https://github.com/professorwug/della_wonders"
license = "MIT"
readme = "README.md"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge"
]

[package.host-dependencies]
python = ">=3.11"
hatchling = "*"
pip = "*"

[package.run-dependencies]
python = ">=3.11"
mitmproxy = ">=10.1.0"
requests = ">=2.31.0"

# Platform-specific configurations (if needed)
# [package.target.linux-64.run-dependencies]
# [package.target.osx-64.run-dependencies]
# [package.target.osx-arm64.run-dependencies]
# [package.target.win-64.run-dependencies]

# Development environment tasks
[tasks]
install = "pip install -e ."
test-install = "pip install -e . && wonder_run --help"
test-commands = "wonder_run --help && start_wonders --help && wonder_status --help && wonders_version"
run-test = "wonder_run test/test_script.py"
comps-test = "wonder_run test/comps_test.py"
clean = "find . -maxdepth 1 -name 'della-wonders-*.conda' -delete || true; find . -maxdepth 1 -name 'info-della-wonders-*.tar.zst' -delete || true"
build = "find . -maxdepth 1 -name 'della-wonders-*.conda' -delete || true; find . -maxdepth 1 -name 'info-della-wonders-*.tar.zst' -delete || true; pixi build"
upload-conda = "./upload_conda.sh"

# Development dependencies
[dependencies]
python = ">=3.11"
mitmproxy = ">=10.1.0"
requests = ">=2.31.0"
pip = "*"
python-dotenv = ">=1.1.1,<2"
python-dateutil = ">=2.9.0.post0,<3"
anaconda-client = "*"
della-wonders = ">=1.0.0,<2"
conda-build = ">=25.5.0,<26"

[pypi-dependencies]
della-wonders = { path = ".", editable = true }
