package:
  name: della-wonders
  version: "1.0.0"

source:
  path: .

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - wonder_run = della_wonders.cli:wonder_run
    - start_wonders = della_wonders.cli:start_wonders
    - wonder_status = della_wonders.cli:wonder_status
    - wonder_bread = della_wonders.cli:wonder_bread

requirements:
  host:
    - python >=3.11
    - pip
    - hatchling
  run:
    - python >=3.11
    - mitmproxy >=10.1.0
    - requests >=2.31.0

test:
  imports:
    - della_wonders
  commands:
    - wonder_run --help
    - start_wonders --help
    - wonder_status --help
    - wonder_bread

about:
  home: https://github.com/professorwug/della_wonders
  license: MIT
  license_file: LICENSE
  summary: Store-and-forward HTTP proxy for airgapped environments
  description: |
    Della Wonders is a store-and-forward HTTP proxy system designed for 
    airgapped environments. It allows secure HTTP request/response 
    communication across air gaps using file-based message passing.
  dev_url: https://github.com/professorwug/della_wonders
  doc_url: https://github.com/professorwug/della_wonders

extra:
  recipe-maintainers:
    - professorwug